name: test the pull request

on:
  push:
    branches: 
      - main
  pull_request_target:
    branches: 
      - main

jobs:
  test_and_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: List the changed files and run the pytest
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # if file name is `tests/test_*.py`
            if [[ $file == tests/test_*.py ]]; then
              echo "$file was changed"
              # requirements file name is  `requirements/*_requirements.txt`
              requirements_file_name=$(echo $file | sed -e "s/tests\/test_\(.*\).py/requirements\/\1_requirements.txt/")
              pip install -r $requirements_file_name
              # run pytest
              pytest $file::test_inference
              # if the test is not succeed, exit with -1
              if [[ $? -ne 0 ]]; then
                exit -1
              fi
            fi
            # if the file name has folder `.github/workflows/`, exit with -1
            if [[ $file == .github/workflows/* ]]; then
              echo "$file was changed, not approved"
              exit -1
            fi
          done
        
